#!/usr/bin/env bash
# tmux-powerkit theme — generated by aibox CLI from the active theme palette.
# Loaded via @powerkit_theme "custom" + @powerkit_custom_theme_path.
# Do NOT edit; re-run `aibox theme` to regenerate.

declare -gA THEME_COLORS=(
    # Core
    [background]="#0E1720"

    # Status bar
    [statusbar-bg]="#131E2B"
    [statusbar-fg]="#C5DAF0"

    # Session (status-left)
    [session-bg]="#E05232"
    [session-fg]="#0E1720"
    [session-prefix-bg]="#E55B5B"
    [session-copy-bg]="#8AACC8"
    [session-search-bg]="#E0B85B"
    [session-command-bg]="#E3574A"

    # Windows
    [window-active-base]="#E05232"
    [window-active-style]="bold"
    [window-inactive-base]="#7B8DA3"
    [window-inactive-style]="none"
    [window-activity-style]="italics"
    [window-bell-style]="bold"
    [window-zoomed-bg]="#8AACC8"

    # Panes
    [pane-border-active]="#E05232"
    [pane-border-inactive]="#7B8DA3"

    # Health / state segments (chevron color rotation source)
    [ok-base]="#9E787B"
    [good-base]="#4FB07A"
    [info-base]="#8AACC8"
    [warning-base]="#E0B85B"
    [error-base]="#E55B5B"
    [disabled-base]="#7B8DA3"

    # Messages
    [message-bg]="#131E2B"
    [message-fg]="#C5DAF0"

    # Popup & menu
    [popup-bg]="#131E2B"
    [popup-fg]="#C5DAF0"
    [popup-border]="#E05232"
    [menu-bg]="#131E2B"
    [menu-fg]="#C5DAF0"
    [menu-selected-bg]="#E05232"
    [menu-selected-fg]="#0E1720"
    [menu-border]="#E05232"
)

# Extra slots some plugins read directly — also derived from the palette so
# every chevron lands on a known-good bg.
declare -gA THEME_EXTRA=(
    [orange]="#F2A65A"
    [magenta]="#E3574A"
    [surface]="#131E2B"
)
