// Generate the downloadable token files in brand/tokens/ from src/data/brand.yaml.
//
// brand/tokens/* are what a consumer downloads and what the documentation links
// to. They used to be maintained by hand, which is why they had drifted badly:
// neither variables.css nor tokens.json carried a single one of the three
// 12-step scales, tailwind.config.js carried the light scales but no dark ones
// and no terminal palette, and none of the three carried the semantic colours.
//
// They are generated now, from the same file the documentation renders from, so
// a page and a download cannot disagree. scripts/check-tokens.sh verifies both
// that brand.yaml agrees with the SCSS that actually styles the site, and that
// the committed files match a fresh generation.
//
//   node scripts/build-tokens.mjs           # write
//   node scripts/build-tokens.mjs --out DIR # write elsewhere (used by the check)

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";
import { parse } from "yaml";

const ROOT = new URL("..", import.meta.url).pathname.replace(/\/$/, "");
const args = process.argv.slice(2);
const outIdx = args.indexOf("--out");
const OUT = outIdx === -1 ? join(ROOT, "brand", "tokens") : args[outIdx + 1];
mkdirSync(OUT, { recursive: true });

const brand = parse(readFileSync(join(ROOT, "src/data/brand.yaml"), "utf8"));

const BANNER_LINES = [
  "projectious.work brand tokens",
  "",
  "GENERATED by scripts/build-tokens.mjs from src/data/brand.yaml.",
  "Do not edit by hand — edit brand.yaml and regenerate, or the next run",
  "silently reverts the change. scripts/check-tokens.sh enforces this.",
];

const SCALES = ["midnight", "orange", "slate"];

// -----------------------------------------------------------------------------
// variables.css
// -----------------------------------------------------------------------------
function css() {
  const L = [];
  L.push("/* " + BANNER_LINES[0]);
  for (const l of BANNER_LINES.slice(1)) L.push(l ? `   ${l}` : "");
  L.push("*/", "", ":root {");

  L.push("  /* Named brand colours. Shortcuts into the scales, not a separate palette. */");
  for (const c of brand.core) L.push(`  ${c.token}: ${c.hex};   /* ${c.use} */`);

  L.push("", "  /* The three 12-step scales, light mode. Step roles:");
  L.push("     " + brand.stepRoles.map((r, i) => `${i + 1} ${r.toLowerCase()}`).join(", ") + ".");
  L.push("     Only 11 and 12 are text roles. */");
  for (const name of SCALES) {
    const s = brand.scales[name];
    L.push(`  /* ${s.name} — ${s.note} */`);
    s.light.forEach((hex, i) => L.push(`  --${name}-${i + 1}: ${hex};`));
  }

  L.push("", "  /* Both ramps again under fixed names, so a consumer whose dark mode is a");
  L.push("     class or an attribute this file does not know about can map to them");
  L.push("     directly. The names above swap with the mode; these never do. */");
  for (const name of SCALES) {
    const s = brand.scales[name];
    s.light.forEach((hex, i) => L.push(`  --${name}-light-${i + 1}: ${hex};`));
    s.dark.forEach((hex, i) => L.push(`  --${name}-dark-${i + 1}: ${hex};`));
  }
  for (const s of brand.semantic) {
    const k = s.role.toLowerCase();
    L.push(`  --color-${k}-light: ${s.lightSolid};  --color-${k}-light-bg: ${s.lightTint};  --color-${k}-light-fg: ${s.lightOnTint};`);
    L.push(`  --color-${k}-dark: ${s.darkSolid};  --color-${k}-dark-bg: ${s.darkTint};  --color-${k}-dark-fg: ${s.darkSolid};`);
  }
  for (const s of brand.surfaces) {
    const base = s.token.replace(/^--color-/, "");
    L.push(`  --color-${base}-light: ${s.light};  --color-${base}-dark: ${s.dark};`);
  }

  L.push("", "  /* Semantic colours. `-fg` is the foreground for the matching tint,");
  L.push("     where the solid value does not clear AA against it. */");
  for (const s of brand.semantic) {
    const k = s.role.toLowerCase();
    L.push(`  --color-${k}: ${s.lightSolid};`);
    L.push(`  --color-${k}-bg: ${s.lightTint};`);
    L.push(`  --color-${k}-fg: ${s.lightOnTint};   /* ${s.lightContrast} on the tint */`);
  }

  L.push("", "  /* App surfaces and text */");
  for (const s of brand.surfaces) {
    L.push(`  ${s.token}: ${s.light};${s.contrast ? `   /* ${s.contrast.split(" / ")[0]} */` : ""}`);
  }

  L.push("", "  /* Typography */");
  for (const f of brand.fonts) {
    const key = /Jakarta/.test(f.family) ? "heading" : /Source/.test(f.family) ? "body" : "code";
    const fallback = key === "code" ? "monospace" : "sans-serif";
    L.push(`  --font-${key}: '${f.family}', ${fallback};`);
  }
  L.push("");
  for (const t of brand.type) {
    const k = t.style.toLowerCase().replace(/\s+/g, "-");
    L.push(`  --type-${k}-size: ${t.size}px;  --type-${k}-weight: ${t.weight};  --type-${k}-lh: ${t.lh};`);
  }

  L.push("", `  /* Spacing (${brand.spacing.base}px base) */`);
  brand.spacing.steps.forEach((v, i) => L.push(`  --space-${i + 1}: ${v}px;`));

  L.push("", "  /* Border radius */");
  for (const r of brand.radius) L.push(`  --radius-${r.name}: ${r.value};   /* ${r.use} */`);

  L.push("", "  /* Elevation */");
  for (const e of brand.elevation) L.push(`  --${e.name}: ${e.value};   /* ${e.use} */`);

  L.push("", "  /* Motion */");
  for (const d of brand.motion.durations) L.push(`  --duration-${d.name}: ${d.value};   /* ${d.use} */`);
  for (const e of brand.motion.easing) L.push(`  --${e.name}: ${e.value};   /* ${e.use} */`);

  L.push("", "  /* Breakpoints. Below sm is the base, not a breakpoint. Custom properties");
  L.push("     cannot be used in a media query, so these are for calc() and JS; the");
  L.push("     queries themselves have to be written out. */");
  for (const b of brand.breakpoints) L.push(`  --breakpoint-${b.name}: ${b.value}px;   /* ${b.use} */`);

  L.push("", `  /* Terminal — one dark surface, sixteen ANSI slots plus chrome.`);
  L.push(`     Measured against --terminal-surface; floor ${brand.terminal.floor}. */`);
  L.push(`  --terminal-surface: ${brand.terminal.surface};`);
  for (const a of brand.terminal.ansi) L.push(`  --terminal-ansi-${a.slot}: ${a.normal};   /* ${a.name} */`);
  for (const a of brand.terminal.ansi) L.push(`  --terminal-ansi-${a.slot + 8}: ${a.bright};   /* bright ${a.name} */`);
  for (const c of brand.terminal.chrome) {
    L.push(`  --terminal-${slug(c.role)}: ${c.hex};`);
  }
  L.push("}");

  L.push("", "/* Dark mode. The scales, the semantic colours and the surface aliases all");
  L.push("   have a dark variant; everything else is mode-independent. Step 9 is");
  L.push("   constant across modes by design. */");
  const darkBody = [];
  for (const name of SCALES) {
    darkBody.push(`  /* ${brand.scales[name].name} */`);
    brand.scales[name].dark.forEach((hex, i) => darkBody.push(`  --${name}-${i + 1}: ${hex};`));
  }
  darkBody.push("");
  for (const s of brand.semantic) {
    const k = s.role.toLowerCase();
    darkBody.push(`  --color-${k}: ${s.darkSolid};`);
    darkBody.push(`  --color-${k}-bg: ${s.darkTint};`);
    darkBody.push(`  --color-${k}-fg: ${s.darkSolid};   /* ${s.darkContrast} on the tint */`);
  }
  darkBody.push("");
  for (const s of brand.surfaces) {
    darkBody.push(`  ${s.token}: ${s.dark};${s.contrast ? `   /* ${s.contrast.split(" / ")[1]} */` : ""}`);
  }

  // Emitted twice: once following the OS preference, once under an explicit
  // [data-theme="dark"] so a consumer with a theme toggle can force it. A
  // toggle that only works when the OS already agrees is not a toggle.
  L.push("@media (prefers-color-scheme: dark) {", "  :root {");
  L.push(...darkBody.map((l) => (l ? "  " + l : l)));
  L.push("  }", "}");
  L.push("", '[data-theme="dark"] {');
  L.push(...darkBody);
  L.push("}", "");
  return L.join("\n");
}

const slug = (s) =>
  s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");

// -----------------------------------------------------------------------------
// tokens.json — Style Dictionary shape: every leaf is { value, comment? }
// -----------------------------------------------------------------------------
function json() {
  const v = (value, comment) => (comment ? { value, comment } : { value });
  const out = {
    $description: BANNER_LINES.filter(Boolean).join(" "),
    color: {},
    scale: {},
    semantic: {},
    surface: {},
    font: {},
    type: {},
    spacing: {},
    radius: {},
    elevation: {},
    motion: { duration: {}, easing: {} },
    breakpoint: {},
    terminal: {},
  };

  for (const c of brand.core) {
    out.color[camel(c.token.replace(/^--color-/, ""))] = v(c.hex, c.use);
  }
  for (const name of SCALES) {
    const s = brand.scales[name];
    out.scale[name] = { $description: s.note, light: {}, dark: {} };
    s.light.forEach((hex, i) => (out.scale[name].light[i + 1] = v(hex, brand.stepRoles[i])));
    s.dark.forEach((hex, i) => (out.scale[name].dark[i + 1] = v(hex, brand.stepRoles[i])));
  }
  for (const s of brand.semantic) {
    out.semantic[s.role.toLowerCase()] = {
      $description: s.use,
      light: { solid: v(s.lightSolid), tint: v(s.lightTint), onTint: v(s.lightOnTint, `${s.lightContrast} on the tint`) },
      dark: { solid: v(s.darkSolid), tint: v(s.darkTint), onTint: v(s.darkSolid, `${s.darkContrast} on the tint`) },
    };
  }
  for (const s of brand.surfaces) {
    out.surface[camel(s.token.replace(/^--color-/, ""))] = {
      light: v(s.light), dark: v(s.dark),
      ...(s.contrast ? { $comment: `${s.use} — ${s.contrast}` } : { $comment: s.use }),
    };
  }
  for (const f of brand.fonts) {
    const key = /Jakarta/.test(f.family) ? "heading" : /Source/.test(f.family) ? "body" : "code";
    out.font[key] = v(`'${f.family}', ${key === "code" ? "monospace" : "sans-serif"}`, `${f.role} — ${f.license}`);
  }
  for (const t of brand.type) {
    out.type[camel(t.style)] = { size: v(`${t.size}px`), weight: v(String(t.weight)), lineHeight: v(String(t.lh)) };
  }
  brand.spacing.steps.forEach((s, i) => (out.spacing[i + 1] = v(`${s}px`)));
  for (const r of brand.radius) out.radius[r.name] = v(r.value, r.use);
  for (const e of brand.elevation) out.elevation[e.name.replace("shadow-", "")] = v(e.value, e.use);
  for (const d of brand.motion.durations) out.motion.duration[d.name] = v(d.value, d.use);
  for (const e of brand.motion.easing) out.motion.easing[camel(e.name)] = v(e.value, e.use);
  for (const b of brand.breakpoints) out.breakpoint[b.name] = v(`${b.value}px`, b.use);

  out.terminal.surface = v(brand.terminal.surface, "The terminal has one surface and it does not follow a light mode");
  for (const a of brand.terminal.ansi) {
    out.terminal[`ansi${a.slot}`] = v(a.normal, `${a.name} — ${a.normalContrast} on surface`);
    out.terminal[`ansi${a.slot + 8}`] = v(a.bright, `bright ${a.name} — ${a.brightContrast} on surface`);
  }
  for (const c of brand.terminal.chrome) {
    out.terminal[camel(c.role)] = v(c.hex, `${c.role} — ${c.contrast}`);
  }
  return JSON.stringify(out, null, 2) + "\n";
}

const camel = (s) =>
  s.toLowerCase().replace(/[^a-z0-9]+(.)/g, (_, c) => c.toUpperCase()).replace(/[^a-z0-9]/gi, "");

// -----------------------------------------------------------------------------
// tailwind.config.js
// -----------------------------------------------------------------------------
function tailwind() {
  const L = [];
  L.push("/**");
  for (const l of BANNER_LINES) L.push(l ? ` * ${l}` : " *");
  L.push(" *");
  L.push(" * Both modes are present. Tailwind has no built-in notion of a colour mode,");
  L.push(" * so the dark scales are exposed as their own `*Dark` keys rather than being");
  L.push(" * swapped in behind `dark:` — a consumer wires them up with whatever dark");
  L.push(" * strategy their project already uses.");
  L.push(" *");
  L.push(" * @type {import('tailwindcss').Config}");
  L.push(" */");
  L.push("module.exports = {", "  theme: {", "    extend: {", "      colors: {");

  const alias = { midnight: "primary", orange: "accent", slate: "secondary" };
  for (const name of SCALES) {
    const s = brand.scales[name];
    const core = brand.core.filter((c) => c.token.includes(alias[name]));
    L.push(`        // ${s.name} — ${s.note}`);
    L.push(`        ${name}: {`);
    for (const c of core) {
      const key = c.token.replace(`--color-${alias[name]}`, "").replace(/^-/, "") || "DEFAULT";
      L.push(`          ${key}: '${c.hex}',   // ${c.use}`);
    }
    L.push("          " + row(s.light, 1, 6));
    L.push("          " + row(s.light, 7, 12));
    L.push("        },");
    L.push(`        ${name}Dark: {`);
    L.push("          " + row(s.dark, 1, 6));
    L.push("          " + row(s.dark, 7, 12));
    L.push("        },");
  }

  L.push("        // Semantic. `fg` is the foreground for the matching `bg` tint.");
  for (const s of brand.semantic) {
    const k = s.role.toLowerCase();
    L.push(`        ${k}: { DEFAULT: '${s.lightSolid}', bg: '${s.lightTint}', fg: '${s.lightOnTint}' },`);
    L.push(`        ${k}Dark: { DEFAULT: '${s.darkSolid}', bg: '${s.darkTint}', fg: '${s.darkSolid}' },`);
  }

  L.push("        // Terminal — one dark surface, sixteen ANSI slots plus chrome.");
  L.push("        terminal: {");
  L.push(`          surface: '${brand.terminal.surface}',`);
  for (const a of brand.terminal.ansi) {
    L.push(`          ansi${a.slot}: '${a.normal}', ansi${a.slot + 8}: '${a.bright}',   // ${a.name}`);
  }
  for (const c of brand.terminal.chrome) L.push(`          ${camel(c.role)}: '${c.hex}',`);
  L.push("        },");
  L.push("      },");

  L.push("      fontFamily: {");
  for (const f of brand.fonts) {
    const key = /Jakarta/.test(f.family) ? "heading" : /Source/.test(f.family) ? "body" : "mono";
    L.push(`        ${key}: ['${f.family}', '${key === "mono" ? "monospace" : "sans-serif"}'],   // ${f.role}`);
  }
  L.push("      },");

  L.push("      fontSize: {");
  for (const t of brand.type) {
    L.push(`        ${camel(t.style)}: ['${t.size}px', { lineHeight: '${t.lh}', fontWeight: '${t.weight}' }],`);
  }
  L.push("      },");

  L.push("      spacing: {");
  L.push("        " + brand.spacing.steps.map((s, i) => `${i + 1}: '${s}px'`).join(", ") + ",");
  L.push("      },");

  L.push("      borderRadius: {");
  for (const r of brand.radius) L.push(`        ${r.name}: '${r.value}',   // ${r.use}`);
  L.push("      },");

  L.push("      boxShadow: {");
  for (const e of brand.elevation) L.push(`        ${e.name.replace("shadow-", "")}: '${e.value}',   // ${e.use}`);
  L.push("      },");

  L.push("      transitionDuration: {");
  for (const d of brand.motion.durations) L.push(`        ${d.name}: '${d.value}',`);
  L.push("      },");
  L.push("      transitionTimingFunction: {");
  for (const e of brand.motion.easing) L.push(`        ${camel(e.name)}: '${e.value}',`);
  L.push("      },");
  L.push("      screens: {");
  for (const b of brand.breakpoints) L.push(`        ${b.name}: '${b.value}px',   // ${b.use}`);
  L.push("      },");
  L.push("    },", "  },", "};", "");
  return L.join("\n");
}

const row = (arr, from, to) =>
  arr.slice(from - 1, to).map((h, i) => `${from + i}: '${h}'`).join(", ") + ",";

// -----------------------------------------------------------------------------

writeFileSync(join(OUT, "variables.css"), css());
writeFileSync(join(OUT, "tokens.json"), json());
writeFileSync(join(OUT, "tailwind.config.js"), tailwind());
console.log(`Wrote variables.css, tokens.json and tailwind.config.js to ${OUT}`);
