#!/usr/bin/env -S uv run
# /// script
# requires-python = ">=3.10"
# dependencies = ["pyyaml>=6,<7"]
# ///
"""Generate the public token downloads from src/data/brand.yaml."""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
SCALES = ("midnight", "orange", "slate")
BANNER = (
    "projectious.work brand tokens",
    "",
    "GENERATED by scripts/build_tokens.py from src/data/brand.yaml.",
    "Do not edit by hand — edit brand.yaml and regenerate, or the next run",
    "silently reverts the change. scripts/check-tokens.sh enforces this.",
)


def slug(value: str) -> str:
    return re.sub(r"^-|-?$", "", re.sub(r"[^a-z0-9]+", "-", value.lower()))


def camel(value: str) -> str:
    words = re.sub(r"[^a-zA-Z0-9]+", " ", value).strip().split()
    return "" if not words else words[0].lower() + "".join(w.title() for w in words[1:])


def css(brand: dict) -> str:
    lines = ["/* " + BANNER[0]]
    lines.extend(f"   {line}" if line else "" for line in BANNER[1:])
    lines.extend(("*/", "", ":root {"))
    lines.append("  /* Named brand colours. Shortcuts into the scales, not a separate palette. */")
    for item in brand["core"]:
        lines.append(f"  {item['token']}: {item['hex']};   /* {item['use']} */")
    lines.extend(("", "  /* The three 12-step scales, light mode. Step roles:"))
    roles = ", ".join(f"{i} {role.lower()}" for i, role in enumerate(brand["stepRoles"], 1))
    lines.extend((f"     {roles}.", "     Only 11 and 12 are text roles. */"))
    for name in SCALES:
        scale = brand["scales"][name]
        lines.append(f"  /* {scale['name']} — {scale['note']} */")
        lines.extend(f"  --{name}-{i}: {value};" for i, value in enumerate(scale["light"], 1))
    lines.extend(("", "  /* Both ramps again under fixed names, so a consumer whose dark mode is a"))
    lines.extend(("     class or an attribute this file does not know about can map to them", "     directly. The names above swap with the mode; these never do. */"))
    for name in SCALES:
        scale = brand["scales"][name]
        lines.extend(f"  --{name}-light-{i}: {value};" for i, value in enumerate(scale["light"], 1))
        lines.extend(f"  --{name}-dark-{i}: {value};" for i, value in enumerate(scale["dark"], 1))
    for item in brand["semantic"]:
        key = item["role"].lower()
        lines.append(f"  --color-{key}-light: {item['lightSolid']};  --color-{key}-light-bg: {item['lightTint']};  --color-{key}-light-fg: {item['lightOnTint']};")
        lines.append(f"  --color-{key}-dark: {item['darkSolid']};  --color-{key}-dark-bg: {item['darkTint']};  --color-{key}-dark-fg: {item['darkSolid']};")
    for item in brand["surfaces"]:
        key = re.sub(r"^--color-", "", item["token"])
        lines.append(f"  --color-{key}-light: {item['light']};  --color-{key}-dark: {item['dark']};")
    lines.extend(("", "  /* Semantic colours. `-fg` is the foreground for the matching tint,", "     where the solid value does not clear AA against it. */"))
    for item in brand["semantic"]:
        key = item["role"].lower()
        lines.extend((f"  --color-{key}: {item['lightSolid']};", f"  --color-{key}-bg: {item['lightTint']};", f"  --color-{key}-fg: {item['lightOnTint']};   /* {item['lightContrast']} on the tint */"))
    lines.extend(("", "  /* App surfaces and text */"))
    for item in brand["surfaces"]:
        note = f"   /* {item['contrast'].split(' / ')[0]} */" if item.get("contrast") else ""
        lines.append(f"  {item['token']}: {item['light']};{note}")
    lines.extend(("", "  /* Typography */"))
    for font in brand["fonts"]:
        key = "heading" if "Jakarta" in font["family"] else "body" if "Source" in font["family"] else "code"
        fallback = "monospace" if key == "code" else "sans-serif"
        lines.append(f"  --font-{key}: '{font['family']}', {fallback};")
    lines.append("")
    for item in brand["type"]:
        key = re.sub(r"\s+", "-", item["style"].lower())
        lines.append(f"  --type-{key}-size: {item['size']}px;  --type-{key}-weight: {item['weight']};  --type-{key}-lh: {item['lh']};")
    lines.extend(("", f"  /* Spacing ({brand['spacing']['base']}px base) */"))
    lines.extend(f"  --space-{i}: {value}px;" for i, value in enumerate(brand["spacing"]["steps"], 1))
    lines.extend(("", "  /* Border radius */"))
    lines.extend(f"  --radius-{item['name']}: {item['value']};   /* {item['use']} */" for item in brand["radius"])
    lines.extend(("", "  /* Elevation */"))
    lines.extend(f"  --{item['name']}: {item['value']};   /* {item['use']} */" for item in brand["elevation"])
    lines.extend(("", "  /* Motion */"))
    lines.extend(f"  --duration-{item['name']}: {item['value']};   /* {item['use']} */" for item in brand["motion"]["durations"])
    lines.extend(f"  --{item['name']}: {item['value']};   /* {item['use']} */" for item in brand["motion"]["easing"])
    lines.extend(("", "  /* Breakpoints. Below sm is the base, not a breakpoint. Custom properties", "     cannot be used in a media query, so these are for calc() and JS; the", "     queries themselves have to be written out. */"))
    lines.extend(f"  --breakpoint-{item['name']}: {item['value']}px;   /* {item['use']} */" for item in brand["breakpoints"])
    terminal = brand["terminal"]
    lines.extend(("", "  /* Terminal — one dark surface, sixteen ANSI slots plus chrome.", f"     Measured against --terminal-surface; floor {terminal['floor']}. */", f"  --terminal-surface: {terminal['surface']};"))
    lines.extend(f"  --terminal-ansi-{item['slot']}: {item['normal']};   /* {item['name']} */" for item in terminal["ansi"])
    lines.extend(f"  --terminal-ansi-{item['slot'] + 8}: {item['bright']};   /* bright {item['name']} */" for item in terminal["ansi"])
    lines.extend(f"  --terminal-{slug(item['role'])}: {item['hex']};" for item in terminal["chrome"])
    lines.append("}")
    dark: list[str] = []
    for name in SCALES:
        dark.append(f"  /* {brand['scales'][name]['name']} */")
        dark.extend(f"  --{name}-{i}: {value};" for i, value in enumerate(brand["scales"][name]["dark"], 1))
    dark.append("")
    for item in brand["semantic"]:
        key = item["role"].lower()
        dark.extend((f"  --color-{key}: {item['darkSolid']};", f"  --color-{key}-bg: {item['darkTint']};", f"  --color-{key}-fg: {item['darkSolid']};   /* {item['darkContrast']} on the tint */"))
    dark.append("")
    for item in brand["surfaces"]:
        note = f"   /* {item['contrast'].split(' / ')[1]} */" if item.get("contrast") else ""
        dark.append(f"  {item['token']}: {item['dark']};{note}")
    lines.extend(("", "/* Dark mode. The scales, the semantic colours and the surface aliases all", "   have a dark variant; everything else is mode-independent. Step 9 is", "   constant across modes by design. */", "@media (prefers-color-scheme: dark) {", "  :root {"))
    lines.extend("  " + line if line else line for line in dark)
    lines.extend(("  }", "}", "", '[data-theme="dark"] {', *dark, "}", ""))
    return "\n".join(lines)


def value(item, comment=None):
    return {"value": item, **({"comment": comment} if comment else {})}


def token_json(brand: dict) -> str:
    out = {"$description": " ".join(filter(None, BANNER)), "color": {}, "scale": {}, "semantic": {}, "surface": {}, "font": {}, "type": {}, "spacing": {}, "radius": {}, "elevation": {}, "motion": {"duration": {}, "easing": {}}, "breakpoint": {}, "terminal": {}}
    for item in brand["core"]:
        out["color"][camel(re.sub(r"^--color-", "", item["token"]))] = value(item["hex"], item["use"])
    for name in SCALES:
        scale = brand["scales"][name]
        out["scale"][name] = {"$description": scale["note"], "light": {}, "dark": {}}
        for mode in ("light", "dark"):
            for i, hex_value in enumerate(scale[mode], 1):
                out["scale"][name][mode][str(i)] = value(hex_value, brand["stepRoles"][i - 1])
    for item in brand["semantic"]:
        out["semantic"][item["role"].lower()] = {"$description": item["use"], "light": {"solid": value(item["lightSolid"]), "tint": value(item["lightTint"]), "onTint": value(item["lightOnTint"], f"{item['lightContrast']} on the tint")}, "dark": {"solid": value(item["darkSolid"]), "tint": value(item["darkTint"]), "onTint": value(item["darkSolid"], f"{item['darkContrast']} on the tint")}}
    for item in brand["surfaces"]:
        out["surface"][camel(re.sub(r"^--color-", "", item["token"]))] = {"light": value(item["light"]), "dark": value(item["dark"]), "$comment": f"{item['use']} — {item['contrast']}" if item.get("contrast") else item["use"]}
    for font in brand["fonts"]:
        key = "heading" if "Jakarta" in font["family"] else "body" if "Source" in font["family"] else "code"
        out["font"][key] = value(f"'{font['family']}', {'monospace' if key == 'code' else 'sans-serif'}", f"{font['role']} — {font['license']}")
    for item in brand["type"]:
        out["type"][camel(item["style"])] = {"size": value(f"{item['size']}px"), "weight": value(str(item["weight"])), "lineHeight": value(str(item["lh"]))}
    for i, spacing in enumerate(brand["spacing"]["steps"], 1): out["spacing"][str(i)] = value(f"{spacing}px")
    for item in brand["radius"]: out["radius"][item["name"]] = value(item["value"], item["use"])
    for item in brand["elevation"]: out["elevation"][item["name"].replace("shadow-", "")] = value(item["value"], item["use"])
    for item in brand["motion"]["durations"]: out["motion"]["duration"][item["name"]] = value(item["value"], item["use"])
    for item in brand["motion"]["easing"]: out["motion"]["easing"][camel(item["name"])] = value(item["value"], item["use"])
    for item in brand["breakpoints"]: out["breakpoint"][item["name"]] = value(f"{item['value']}px", item["use"])
    terminal = brand["terminal"]
    out["terminal"]["surface"] = value(terminal["surface"], "The terminal has one surface and it does not follow a light mode")
    for item in terminal["ansi"]:
        out["terminal"][f"ansi{item['slot']}"] = value(item["normal"], f"{item['name']} — {item['normalContrast']} on surface")
        out["terminal"][f"ansi{item['slot'] + 8}"] = value(item["bright"], f"bright {item['name']} — {item['brightContrast']} on surface")
    for item in terminal["chrome"]: out["terminal"][camel(item["role"])] = value(item["hex"], f"{item['role']} — {item['contrast']}")
    return json.dumps(out, indent=2, ensure_ascii=False) + "\n"


def row(values, start, end):
    return ", ".join(f"{i}: '{values[i - 1]}'" for i in range(start, end + 1)) + ","


def tailwind(brand: dict) -> str:
    lines = ["/**", *(f" * {line}" if line else " *" for line in BANNER), " *", " * Both modes are present. Tailwind has no built-in notion of a colour mode,", " * so the dark scales are exposed as their own `*Dark` keys rather than being", " * swapped in behind `dark:` — a consumer wires them up with whatever dark", " * strategy their project already uses.", " *", " * @type {import('tailwindcss').Config}", " */", "module.exports = {", "  theme: {", "    extend: {", "      colors: {"]
    aliases = {"midnight": "primary", "orange": "accent", "slate": "secondary"}
    for name in SCALES:
        scale, alias = brand["scales"][name], aliases[name]
        lines.extend((f"        // {scale['name']} — {scale['note']}", f"        {name}: {{"))
        for item in (c for c in brand["core"] if alias in c["token"]):
            key = item["token"].replace(f"--color-{alias}", "").lstrip("-") or "DEFAULT"
            lines.append(f"          {key}: '{item['hex']}',   // {item['use']}")
        lines.extend(("          " + row(scale["light"], 1, 6), "          " + row(scale["light"], 7, 12), "        },", f"        {name}Dark: {{", "          " + row(scale["dark"], 1, 6), "          " + row(scale["dark"], 7, 12), "        },"))
    lines.append("        // Semantic. `fg` is the foreground for the matching `bg` tint.")
    for item in brand["semantic"]:
        key = item["role"].lower()
        lines.extend((f"        {key}: {{ DEFAULT: '{item['lightSolid']}', bg: '{item['lightTint']}', fg: '{item['lightOnTint']}' }},", f"        {key}Dark: {{ DEFAULT: '{item['darkSolid']}', bg: '{item['darkTint']}', fg: '{item['darkSolid']}' }},"))
    terminal = brand["terminal"]
    lines.extend(("        // Terminal — one dark surface, sixteen ANSI slots plus chrome.", "        terminal: {", f"          surface: '{terminal['surface']}',"))
    for item in terminal["ansi"]: lines.append(f"          ansi{item['slot']}: '{item['normal']}', ansi{item['slot'] + 8}: '{item['bright']}',   // {item['name']}")
    for item in terminal["chrome"]: lines.append(f"          {camel(item['role'])}: '{item['hex']}',")
    lines.extend(("        },", "      },", "      fontFamily: {"))
    for font in brand["fonts"]:
        key = "heading" if "Jakarta" in font["family"] else "body" if "Source" in font["family"] else "mono"
        lines.append(f"        {key}: ['{font['family']}', '{'monospace' if key == 'mono' else 'sans-serif'}'],   // {font['role']}")
    lines.extend(("      },", "      fontSize: {"))
    for item in brand["type"]: lines.append(f"        {camel(item['style'])}: ['{item['size']}px', {{ lineHeight: '{item['lh']}', fontWeight: '{item['weight']}' }}],")
    lines.extend(("      },", "      spacing: {", "        " + ", ".join(f"{i}: '{v}px'" for i, v in enumerate(brand["spacing"]["steps"], 1)) + ",", "      },", "      borderRadius: {"))
    for item in brand["radius"]: lines.append(f"        {item['name']}: '{item['value']}',   // {item['use']}")
    lines.extend(("      },", "      boxShadow: {"))
    for item in brand["elevation"]: lines.append(f"        {item['name'].replace('shadow-', '')}: '{item['value']}',   // {item['use']}")
    lines.extend(("      },", "      transitionDuration: {"))
    for item in brand["motion"]["durations"]: lines.append(f"        {item['name']}: '{item['value']}',")
    lines.extend(("      },", "      transitionTimingFunction: {"))
    for item in brand["motion"]["easing"]: lines.append(f"        {camel(item['name'])}: '{item['value']}',")
    lines.extend(("      },", "      screens: {"))
    for item in brand["breakpoints"]: lines.append(f"        {item['name']}: '{item['value']}px',   // {item['use']}")
    lines.extend(("      },", "    },", "  },", "};", ""))
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--out", type=Path, default=ROOT / "src/static/downloads/tokens")
    args = parser.parse_args()
    args.out.mkdir(parents=True, exist_ok=True)
    brand = yaml.safe_load((ROOT / "src/data/brand.yaml").read_text())
    (args.out / "variables.css").write_text(css(brand))
    (args.out / "tokens.json").write_text(token_json(brand))
    (args.out / "tailwind.config.js").write_text(tailwind(brand))
    print(f"Wrote variables.css, tokens.json and tailwind.config.js to {args.out}")


if __name__ == "__main__":
    main()
