#!/usr/bin/env -S uv run
# /// script
# requires-python = ">=3.10"
# dependencies = ["pyyaml>=6,<7"]
# ///
"""Generate the public token downloads from src/data/brand.yaml."""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
SCALES = ("midnight", "orange", "slate")
NAVY_MIDNIGHT = ("#132440", "#1a2b3e", "#20354d", "#263f5a", "#2e4b68")
BANNER = (
    "projectious.work brand tokens",
    "",
    "GENERATED by scripts/build_tokens.py from src/data/brand.yaml.",
    "Do not edit by hand — edit brand.yaml and regenerate, or the next run",
    "silently reverts the change. scripts/check-tokens.sh enforces this.",
)


def slug(value: str) -> str:
    value = re.sub(r"(?<=[a-z0-9])(?=[A-Z])", "-", value)
    return re.sub(r"^-|-?$", "", re.sub(r"[^a-z0-9]+", "-", value.lower()))


def camel(value: str) -> str:
    words = re.sub(r"[^a-zA-Z0-9]+", " ", value).strip().split()
    return "" if not words else words[0].lower() + "".join(w.title() for w in words[1:])


def css(brand: dict) -> str:
    lines = ["/* " + BANNER[0]]
    lines.extend(f"   {line}" if line else "" for line in BANNER[1:])
    lines.extend(("*/", "", ":root {"))
    lines.append("  /* Named brand colours. Shortcuts into the scales, not a separate palette. */")
    for item in brand["core"]:
        lines.append(f"  {item['token']}: {item['hex']};   /* {item['use']} */")
    lines.extend(("", "  /* The three 12-step scales, light mode. Step roles:"))
    roles = ", ".join(f"{i} {role.lower()}" for i, role in enumerate(brand["stepRoles"], 1))
    lines.extend((f"     {roles}.", "     Only 11 and 12 are text roles. */"))
    for name in SCALES:
        scale = brand["scales"][name]
        lines.append(f"  /* {scale['name']} — {scale['note']} */")
        lines.extend(f"  --{name}-{i}: {value};" for i, value in enumerate(scale["light"], 1))
    lines.extend(("", "  /* Appearance-pinned ramps for consumers with their own selector strategy.", "     The names above swap with the appearance; these never do. */"))
    for name in SCALES:
        scale = brand["scales"][name]
        lines.extend(f"  --{name}-light-{i}: {value};" for i, value in enumerate(scale["light"], 1))
        lines.extend(f"  --{name}-dark-{i}: {value};" for i, value in enumerate(scale["dark"], 1))
    for item in brand["semantic"]:
        key = item["role"].lower()
        lines.append(f"  --color-{key}-light: {item['lightSolid']};  --color-{key}-light-bg: {item['lightTint']};  --color-{key}-light-fg: {item['lightOnTint']};")
        lines.append(f"  --color-{key}-dark: {item['darkSolid']};  --color-{key}-dark-bg: {item['darkTint']};  --color-{key}-dark-fg: {item['darkSolid']};")
    for item in brand["surfaces"]:
        key = re.sub(r"^--color-", "", item["token"])
        lines.append(f"  --color-{key}-light: {item['light']};  --color-{key}-navy: {item['navy']};  --color-{key}-deep: {item['deep']};")
    lines.extend(("", "  /* Semantic colours. `-fg` is the foreground for the matching tint,", "     where the solid value does not clear AA against it. */"))
    for item in brand["semantic"]:
        key = item["role"].lower()
        lines.extend((f"  --color-{key}: {item['lightSolid']};", f"  --color-{key}-bg: {item['lightTint']};", f"  --color-{key}-fg: {item['lightOnTint']};   /* {item['lightContrast']} on the tint */"))
    lines.extend(("", "  /* App surfaces and text */"))
    for item in brand["surfaces"]:
        note = f"   /* {item['contrast'].split(' / ')[0]} */" if item.get("contrast") else ""
        lines.append(f"  {item['token']}: {item['light']};{note}")
    lines.extend(("", "  /* Typography */"))
    for font in brand["fonts"]:
        key = "heading" if "Jakarta" in font["family"] else "body" if "Source" in font["family"] else "code"
        fallback = "monospace" if key == "code" else "sans-serif"
        lines.append(f"  --font-{key}: '{font['family']}', {fallback};")
    lines.extend(("", "  /* Layout and portable surface aliases */", "  --font-scale: 1;", "  --container-max: 1100px;", "  --grid-gutter: 16px;", "  --touch-target: 44px;", "  --measure: 65ch;", "  --scrim: rgba(20,36,56,0.72);", "  --code-panel-surface: #131e2b;"))
    for item in brand["type"]:
        key = re.sub(r"\s+", "-", item["style"].lower())
        lines.append(f"  --type-{key}-size: calc({item['size']}px * var(--font-scale));  --type-{key}-weight: {item['weight']};  --type-{key}-lh: {item['lh']};")
    lines.extend(("", f"  /* Spacing ({brand['spacing']['base']}px base) */"))
    lines.extend(f"  --space-{i}: {value}px;" for i, value in enumerate(brand["spacing"]["steps"], 1))
    lines.extend(("", "  /* Border radius */"))
    lines.extend(f"  --radius-{item['name']}: {item['value']};   /* {item['use']} */" for item in brand["radius"])
    lines.extend(("", "  /* Elevation */"))
    lines.extend(f"  --{item['name']}: {item['value']};   /* {item['use']} */" for item in brand["elevation"])
    for i, surface in enumerate(brand["elevationAppearances"]["light"]["surfaces"]):
        lines.append(f"  --elevated-{i}: {surface};")
    for i, rim in enumerate(brand["elevationAppearances"]["light"]["rims"][1:], 1):
        lines.append(f"  --rim-{i}: {rim};")
    lines.extend(("", "  /* Motion */"))
    lines.extend(f"  --duration-{item['name']}: {item['value']};   /* {item['use']} */" for item in brand["motion"]["durations"])
    lines.extend(f"  --{item['name']}: {item['value']};   /* {item['use']} */" for item in brand["motion"]["easing"])
    lines.extend(("", "  /* Breakpoints. Below sm is the base, not a breakpoint. Custom properties", "     cannot be used in a media query, so these are for calc() and JS; the", "     queries themselves have to be written out. */"))
    lines.extend(f"  --breakpoint-{item['name']}: {item['value']}px;   /* {item['use']} */" for item in brand["breakpoints"])
    terminal = brand["terminal"]
    lines.extend(("", "  /* Terminal — one dark surface, sixteen ANSI slots plus chrome.", f"     Measured against --terminal-surface; floor {terminal['floor']}. */", f"  --terminal-surface: {terminal['surface']};"))
    lines.extend(f"  --terminal-ansi-{item['slot']}: {item['normal']};   /* {item['name']} */" for item in terminal["ansi"])
    lines.extend(f"  --terminal-ansi-{item['slot'] + 8}: {item['bright']};   /* bright {item['name']} */" for item in terminal["ansi"])
    lines.extend(f"  --terminal-{slug(item['role'])}: {item['hex']};" for item in terminal["chrome"])
    lines.extend(("", "  /* Optional light code and terminal companions */", f"  --syntax-light-surface: {brand['syntaxLight']['surface']};"))
    lines.extend(f"  {item['token']}: {item['hex']};" for item in brand["syntaxLight"]["roles"])
    light_terminal = brand["terminalLight"]
    lines.append(f"  --terminal-light-surface: {light_terminal['surface']};")
    lines.extend(f"  --terminal-light-ansi-{item['slot']}: {item['hex']};" for item in light_terminal["ansi"])
    lines.extend(f"  --terminal-light-{slug(key)}: {value};" for key, value in light_terminal["chrome"].items())
    lines.append("}")
    dark: list[str] = []
    for name in SCALES:
        dark.append(f"  /* {brand['scales'][name]['name']} */")
        values = list(brand["scales"][name]["dark"])
        if name == "midnight":
            values[:5] = NAVY_MIDNIGHT
        dark.extend(f"  --{name}-{i}: {value};" for i, value in enumerate(values, 1))
    dark.append("")
    for item in brand["semantic"]:
        key = item["role"].lower()
        dark.extend((f"  --color-{key}: {item['darkSolid']};", f"  --color-{key}-bg: {item['darkTint']};", f"  --color-{key}-fg: {item['darkSolid']};   /* {item['darkContrast']} on the tint */"))
    dark.append("")
    for item in brand["surfaces"]:
        note = f"   /* {item['contrast'].split(' / ')[1]} */" if item.get("contrast") else ""
        dark.append(f"  {item['token']}: {item['navy']};{note}")
    dark.extend(("  --surface-2: #20354d;", "  --border-strong: #4d7098;", "  --tag-bg: #20354d;"))
    for i, surface in enumerate(brand["elevationAppearances"]["navy"]["surfaces"]):
        dark.append(f"  --elevated-{i}: {surface};")
    for i, rim in enumerate(brand["elevationAppearances"]["navy"]["rims"][1:], 1):
        dark.append(f"  --rim-{i}: {rim};")
    lines.extend(("", "/* Navy is the default dark appearance. Step 9 remains constant. */", "@media (prefers-color-scheme: dark) {", "  :root {"))
    lines.extend("  " + line if line else line for line in dark)
    deep_elevation = [f"  --elevated-{i}: {surface};" for i, surface in enumerate(brand["elevationAppearances"]["deep"]["surfaces"])]
    lines.extend(("  }", "}", "", '[data-theme="dark"] {', *dark, "}", "", "/* Deep dark overrides exactly the low ramp and aliases derived from it. */", '[data-theme="dark"][data-surface="deep"] {', "  --midnight-1: #0e1720;", "  --midnight-2: #131e2b;", "  --midnight-3: #1a2b3e;", "  --midnight-4: #20354d;", "  --midnight-5: #263f5a;", "  --color-bg: #0e1720;", "  --color-surface: #131e2b;", "  --color-border: #263f5a;", "  --surface-2: #1a2b3e;", "  --border-strong: #3a5c7e;", "  --tag-bg: #1a2b3e;", *deep_elevation, "}", ""))
    return "\n".join(lines)


def value(item, comment=None):
    return {"value": item, **({"comment": comment} if comment else {})}


def token_json(brand: dict) -> str:
    out = {"$description": " ".join(filter(None, BANNER)), "color": {}, "scale": {}, "semantic": {}, "surface": {}, "font": {}, "type": {}, "spacing": {}, "radius": {}, "elevation": {}, "motion": {"duration": {}, "easing": {}}, "breakpoint": {}, "syntax": {"dark": {}, "light": {}}, "terminal": {"dark": {}, "light": {}}}
    for item in brand["core"]:
        out["color"][camel(re.sub(r"^--color-", "", item["token"]))] = value(item["hex"], item["use"])
    for name in SCALES:
        scale = brand["scales"][name]
        out["scale"][name] = {"$description": scale["note"], "light": {}, "navy": {}, "deep": {}}
        modes = {"light": scale["light"], "deep": scale["dark"], "navy": list(scale["dark"])}
        if name == "midnight":
            modes["navy"][:5] = NAVY_MIDNIGHT
        for mode, values in modes.items():
            for i, hex_value in enumerate(values, 1):
                out["scale"][name][mode][str(i)] = value(hex_value, brand["stepRoles"][i - 1])
    for item in brand["semantic"]:
        dark_values = {"solid": value(item["darkSolid"]), "tint": value(item["darkTint"]), "onTint": value(item["darkSolid"], f"{item['darkContrast']} on the tint")}
        out["semantic"][item["role"].lower()] = {"$description": item["use"], "light": {"solid": value(item["lightSolid"]), "tint": value(item["lightTint"]), "onTint": value(item["lightOnTint"], f"{item['lightContrast']} on the tint")}, "navy": dark_values, "deep": dark_values}
    for item in brand["surfaces"]:
        out["surface"][camel(re.sub(r"^--color-", "", item["token"]))] = {"light": value(item["light"]), "navy": value(item["navy"]), "deep": value(item["deep"]), "$comment": f"{item['use']} — {item['contrast']}" if item.get("contrast") else item["use"]}
    for font in brand["fonts"]:
        key = "heading" if "Jakarta" in font["family"] else "body" if "Source" in font["family"] else "code"
        out["font"][key] = value(f"'{font['family']}', {'monospace' if key == 'code' else 'sans-serif'}", f"{font['role']} — {font['license']}")
    for item in brand["type"]:
        out["type"][camel(item["style"])] = {"size": value(f"{item['size']}px"), "weight": value(str(item["weight"])), "lineHeight": value(str(item["lh"]))}
    for i, spacing in enumerate(brand["spacing"]["steps"], 1): out["spacing"][str(i)] = value(f"{spacing}px")
    for item in brand["radius"]: out["radius"][item["name"]] = value(item["value"], item["use"])
    for item in brand["elevation"]: out["elevation"][item["name"].replace("shadow-", "")] = value(item["value"], item["use"])
    out["elevation"]["appearance"] = {}
    for appearance, values in brand["elevationAppearances"].items():
        out["elevation"]["appearance"][appearance] = {"surface": {str(i): value(v) for i, v in enumerate(values["surfaces"])}, "rim": {str(i): value(v) for i, v in enumerate(values["rims"])}}
    for item in brand["motion"]["durations"]: out["motion"]["duration"][item["name"]] = value(item["value"], item["use"])
    for item in brand["motion"]["easing"]: out["motion"]["easing"][camel(item["name"])] = value(item["value"], item["use"])
    for item in brand["breakpoints"]: out["breakpoint"][item["name"]] = value(f"{item['value']}px", item["use"])
    for item in brand["syntax"]:
        out["syntax"]["dark"][camel(item["token"])] = value(item["hex"], f"{item.get('weight', 400)} {item.get('style', 'normal')}")
    out["syntax"]["light"]["surface"] = value(brand["syntaxLight"]["surface"])
    for item in brand["syntaxLight"]["roles"]:
        out["syntax"]["light"][camel(item["role"])] = value(item["hex"])
    terminal = brand["terminal"]
    out["terminal"]["dark"]["surface"] = value(terminal["surface"], "Default terminal surface")
    for item in terminal["ansi"]:
        out["terminal"]["dark"][f"ansi{item['slot']}"] = value(item["normal"], f"{item['name']} — {item['normalContrast']} on surface")
        out["terminal"]["dark"][f"ansi{item['slot'] + 8}"] = value(item["bright"], f"bright {item['name']} — {item['brightContrast']} on surface")
    for item in terminal["chrome"]: out["terminal"]["dark"][camel(item["role"])] = value(item["hex"], f"{item['role']} — {item['contrast']}")
    out["terminal"]["light"]["surface"] = value(brand["terminalLight"]["surface"], "Optional light companion")
    for item in brand["terminalLight"]["ansi"]: out["terminal"]["light"][f"ansi{item['slot']}"] = value(item["hex"], item["name"])
    for key, item in brand["terminalLight"]["chrome"].items(): out["terminal"]["light"][camel(key)] = value(item)
    return json.dumps(out, indent=2, ensure_ascii=False) + "\n"


def row(values, start, end):
    return ", ".join(f"{i}: '{values[i - 1]}'" for i in range(start, end + 1)) + ","


def tailwind(brand: dict) -> str:
    lines = ["/**", *(f" * {line}" if line else " *" for line in BANNER), " *", " * Light, navy, and deep appearances are explicit. A consumer maps these", " * values to its own class or attribute strategy.", " *", " * @type {import('tailwindcss').Config}", " */", "module.exports = {", "  theme: {", "    extend: {", "      colors: {"]
    aliases = {"midnight": "primary", "orange": "accent", "slate": "secondary"}
    for name in SCALES:
        scale, alias = brand["scales"][name], aliases[name]
        lines.extend((f"        // {scale['name']} — {scale['note']}", f"        {name}: {{"))
        for item in (c for c in brand["core"] if alias in c["token"]):
            key = item["token"].replace(f"--color-{alias}", "").lstrip("-") or "DEFAULT"
            lines.append(f"          {key}: '{item['hex']}',   // {item['use']}")
        navy = list(scale["dark"])
        if name == "midnight": navy[:5] = NAVY_MIDNIGHT
        lines.extend(("          " + row(scale["light"], 1, 6), "          " + row(scale["light"], 7, 12), "        },", f"        {name}Navy: {{", "          " + row(navy, 1, 6), "          " + row(navy, 7, 12), "        },", f"        {name}Deep: {{", "          " + row(scale["dark"], 1, 6), "          " + row(scale["dark"], 7, 12), "        },"))
    lines.append("        // Semantic. `fg` is the foreground for the matching `bg` tint.")
    for item in brand["semantic"]:
        key = item["role"].lower()
        lines.extend((f"        {key}: {{ DEFAULT: '{item['lightSolid']}', bg: '{item['lightTint']}', fg: '{item['lightOnTint']}' }},", f"        {key}Navy: {{ DEFAULT: '{item['darkSolid']}', bg: '{item['darkTint']}', fg: '{item['darkSolid']}' }},", f"        {key}Deep: {{ DEFAULT: '{item['darkSolid']}', bg: '{item['darkTint']}', fg: '{item['darkSolid']}' }},"))
    terminal = brand["terminal"]
    lines.extend(("        // Terminal — one dark surface, sixteen ANSI slots plus chrome.", "        terminal: {", f"          surface: '{terminal['surface']}',"))
    for item in terminal["ansi"]: lines.append(f"          ansi{item['slot']}: '{item['normal']}', ansi{item['slot'] + 8}: '{item['bright']}',   // {item['name']}")
    for item in terminal["chrome"]: lines.append(f"          {camel(item['role'])}: '{item['hex']}',")
    lines.extend(("        },", "      },", "      fontFamily: {"))
    for font in brand["fonts"]:
        key = "heading" if "Jakarta" in font["family"] else "body" if "Source" in font["family"] else "mono"
        lines.append(f"        {key}: ['{font['family']}', '{'monospace' if key == 'mono' else 'sans-serif'}'],   // {font['role']}")
    lines.extend(("      },", "      fontSize: {"))
    for item in brand["type"]: lines.append(f"        {camel(item['style'])}: ['{item['size']}px', {{ lineHeight: '{item['lh']}', fontWeight: '{item['weight']}' }}],")
    lines.extend(("      },", "      spacing: {", "        " + ", ".join(f"{i}: '{v}px'" for i, v in enumerate(brand["spacing"]["steps"], 1)) + ",", "      },", "      borderRadius: {"))
    for item in brand["radius"]: lines.append(f"        {item['name']}: '{item['value']}',   // {item['use']}")
    lines.extend(("      },", "      boxShadow: {"))
    for item in brand["elevation"]: lines.append(f"        {item['name'].replace('shadow-', '')}: '{item['value']}',   // {item['use']}")
    lines.extend(("      },", "      transitionDuration: {"))
    for item in brand["motion"]["durations"]: lines.append(f"        {item['name']}: '{item['value']}',")
    lines.extend(("      },", "      transitionTimingFunction: {"))
    for item in brand["motion"]["easing"]: lines.append(f"        {camel(item['name'])}: '{item['value']}',")
    lines.extend(("      },", "      screens: {"))
    for item in brand["breakpoints"]: lines.append(f"        {item['name']}: '{item['value']}px',   // {item['use']}")
    lines.extend(("      },", "    },", "  },", "};", ""))
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--out", type=Path, default=ROOT / "src/static/downloads/tokens")
    args = parser.parse_args()
    args.out.mkdir(parents=True, exist_ok=True)
    brand = yaml.safe_load((ROOT / "src/data/brand.yaml").read_text())
    (args.out / "variables.css").write_text(css(brand))
    (args.out / "tokens.json").write_text(token_json(brand))
    (args.out / "tailwind.config.js").write_text(tailwind(brand))
    print(f"Wrote variables.css, tokens.json and tailwind.config.js to {args.out}")


if __name__ == "__main__":
    main()
