" aibox.vim — generated by aibox CLI from the active theme palette.
" Do NOT edit; re-run `aibox theme` to regenerate.

hi clear
if exists("syntax_on")
  syntax reset
endif
let g:colors_name = "aibox"
set background=dark

" ── UI chrome ──────────────────────────────────────────────────────────────
hi Normal         guifg=#C5DAF0     guibg=#0E1720     ctermfg=NONE ctermbg=NONE
hi NormalNC       guifg=#C5DAF0     guibg=#0E1720
hi LineNr         guifg=#7B8DA3  guibg=#0E1720
hi CursorLineNr   guifg=#E05232 guibg=#131E2B gui=bold
hi CursorLine     guibg=#131E2B
hi CursorColumn   guibg=#131E2B
hi ColorColumn    guibg=#131E2B
hi VertSplit      guifg=#7B8DA3  guibg=#0E1720
hi WinSeparator   guifg=#7B8DA3  guibg=#0E1720
hi StatusLine     guifg=#0E1720     guibg=#E05232 gui=bold
hi StatusLineNC   guifg=#7B8DA3  guibg=#131E2B
hi TabLine        guifg=#7B8DA3  guibg=#131E2B
hi TabLineFill    guibg=#0E1720
hi TabLineSel     guifg=#0E1720     guibg=#E05232 gui=bold
hi SignColumn     guifg=#7B8DA3  guibg=#0E1720
hi FoldColumn     guifg=#7B8DA3  guibg=#0E1720
hi Folded         guifg=#7B8DA3  guibg=#131E2B
hi NonText        guifg=#7B8DA3
hi EndOfBuffer    guifg=#0E1720     guibg=#0E1720
hi SpecialKey     guifg=#7B8DA3
hi MatchParen     guifg=#E05232 guibg=#131E2B gui=bold,underline
hi Conceal        guifg=#7B8DA3  guibg=#0E1720
hi Directory      guifg=#E05232 gui=bold

" ── Selection / search ────────────────────────────────────────────────────
hi Visual         guibg=#131E2B
hi VisualNOS      guibg=#131E2B
hi Search         guifg=#0E1720     guibg=#E0B85B gui=bold
hi IncSearch      guifg=#0E1720     guibg=#F2A65A gui=bold
hi CurSearch      guifg=#0E1720     guibg=#E05232 gui=bold
hi QuickFixLine   guibg=#131E2B gui=bold

" ── Popup menu ────────────────────────────────────────────────────────────
hi Pmenu          guifg=#C5DAF0     guibg=#131E2B
hi PmenuSel       guifg=#0E1720     guibg=#E05232 gui=bold
hi PmenuSbar      guibg=#131E2B
hi PmenuThumb     guibg=#7B8DA3
hi WildMenu       guifg=#0E1720     guibg=#E05232 gui=bold

" ── Messages ──────────────────────────────────────────────────────────────
hi ErrorMsg       guifg=#E55B5B    gui=bold
hi WarningMsg     guifg=#E0B85B
hi ModeMsg        guifg=#E05232 gui=bold
hi MoreMsg        guifg=#4FB07A
hi Question       guifg=#E05232
hi Title          guifg=#E05232 gui=bold

" ── Syntax (linked groups) ────────────────────────────────────────────────
hi Comment        guifg=#7B8DA3    gui=italic
hi Constant       guifg=#F2A65A
hi String         guifg=#4FB07A
hi Character      guifg=#4FB07A
hi Number         guifg=#F2A65A
hi Boolean        guifg=#F2A65A
hi Float          guifg=#F2A65A
hi Identifier     guifg=#C5DAF0
hi Function       guifg=#E05232
hi Statement      guifg=#E55B5B
hi Conditional    guifg=#E55B5B
hi Repeat         guifg=#E55B5B
hi Label          guifg=#E0B85B
hi Operator       guifg=#8AACC8
hi Keyword        guifg=#E55B5B
hi Exception      guifg=#E55B5B
hi PreProc        guifg=#E0B85B
hi Include        guifg=#E55B5B
hi Define         guifg=#E55B5B
hi Macro          guifg=#E05232
hi PreCondit      guifg=#E0B85B
hi Type           guifg=#E0B85B
hi StorageClass   guifg=#E0B85B
hi Structure      guifg=#E0B85B
hi Typedef        guifg=#E0B85B
hi Special        guifg=#8AACC8
hi SpecialChar    guifg=#F2A65A
hi Tag            guifg=#E05232
hi Delimiter      guifg=#C5DAF0
hi SpecialComment guifg=#7B8DA3    gui=italic
hi Debug          guifg=#F2A65A
hi Underlined     guifg=#E05232   gui=underline
hi Ignore         guifg=#7B8DA3
hi Error          guifg=#E55B5B      gui=bold
hi Todo           guifg=#E0B85B   guibg=#131E2B gui=bold

" ── Diff ──────────────────────────────────────────────────────────────────
hi DiffAdd        guifg=#4FB07A    guibg=#0E1720
hi DiffChange     guifg=#E0B85B   guibg=#0E1720
hi DiffDelete     guifg=#E55B5B      guibg=#0E1720
hi DiffText       guifg=#E05232   guibg=#0E1720    gui=bold
hi diffAdded      guifg=#4FB07A
hi diffRemoved    guifg=#E55B5B
hi diffChanged    guifg=#E0B85B
hi diffFile       guifg=#E05232   gui=bold
hi diffNewFile    guifg=#4FB07A    gui=bold
hi diffOldFile    guifg=#E55B5B      gui=bold
hi diffLine       guifg=#7B8DA3

" ── Spelling ──────────────────────────────────────────────────────────────
hi SpellBad       gui=undercurl guisp=#E55B5B
hi SpellCap       gui=undercurl guisp=#E0B85B
hi SpellLocal     gui=undercurl guisp=#8AACC8
hi SpellRare      gui=undercurl guisp=#E3574A

" ── Git plugins / gitgutter / signify ────────────────────────────────────
hi GitGutterAdd          guifg=#4FB07A    guibg=#0E1720
hi GitGutterChange       guifg=#E0B85B   guibg=#0E1720
hi GitGutterDelete       guifg=#E55B5B      guibg=#0E1720
hi GitGutterChangeDelete guifg=#F2A65A   guibg=#0E1720
hi SignifySignAdd        guifg=#4FB07A    guibg=#0E1720
hi SignifySignChange     guifg=#E0B85B   guibg=#0E1720
hi SignifySignDelete     guifg=#E55B5B      guibg=#0E1720

" ── Markdown ──────────────────────────────────────────────────────────────
hi link markdownH1        Title
hi link markdownH2        Title
hi link markdownH3        Title
hi link markdownH4        Title
hi link markdownCode      String
hi link markdownCodeBlock String
hi link markdownLinkText  Function
hi markdownUrl   guifg=#8AACC8  gui=underline

" ── Vim help ──────────────────────────────────────────────────────────────
hi link helpHyperTextEntry Underlined
hi link helpHyperTextJump  Underlined
hi link helpHeader         Title
hi link helpExample        String
hi link helpOption         Type
hi link helpVim            Identifier

" ── Misc plugins ──────────────────────────────────────────────────────────
hi link NvimTreeFolderName Directory
hi link NvimTreeRootFolder Title
hi link TelescopeBorder    FloatBorder
hi FloatBorder    guifg=#7B8DA3    guibg=#0E1720
hi NormalFloat    guifg=#C5DAF0       guibg=#131E2B
