# Generated by `aibox` — do NOT edit. Re-run `aibox theme` to refresh.
# Exports keep ANSI-colored tools (bat, delta, fzf, eza, less) aligned with
# the active aibox theme.

export BAT_THEME="Coldark-Dark"
export FZF_DEFAULT_OPTS="${FZF_DEFAULT_OPTS:-} --color=bg+:#131E2B,bg:#0E1720,fg:#C5DAF0,fg+:#C5DAF0,hl:#E05232,hl+:#E05232,pointer:#E05232,marker:#4FB07A,spinner:#E05232,info:#7B8DA3,header:#7B8DA3,border:#7B8DA3,prompt:#E05232,query:#C5DAF0,disabled:#7B8DA3,gutter:#0E1720,preview-bg:#0E1720,preview-fg:#C5DAF0,separator:#7B8DA3,label:#E05232"
export EZA_COLORS="di=38;2;224;82;50;1:ex=38;2;79;176;122:ln=38;2;138;172;200:fi=0:or=38;2;229;91;91:mi=38;2;229;91;91:da=38;2;123;141;163:sn=38;2;224;82;50:sb=38;2;224;82;50:uu=38;2;123;141;163:un=38;2;123;141;163:gu=38;2;123;141;163:gn=38;2;123;141;163:ga=38;2;79;176;122:gm=38;2;224;184;91:gd=38;2;229;91;91:gv=38;2;224;184;91:gt=38;2;242;166;90:xx=38;2;123;141;163:da=38;2;123;141;163"

# `less` headings / search hits — match prompt accent / warnings.
export LESS_TERMCAP_md=$'\e[38;2;224;82;50m'    # bold (section headers, command names)
export LESS_TERMCAP_us=$'\e[38;2;224;184;91m'    # underline (options, args)
export LESS_TERMCAP_so=$'\e[38;2;224;82;50;7m'  # reverse (search / status line)
export LESS_TERMCAP_me=$'\e[0m'
export LESS_TERMCAP_ue=$'\e[0m'
export LESS_TERMCAP_se=$'\e[0m'
export GROFF_NO_SGR=1                  # tell groff to emit ANSI, not SGR-bypass
unset LESS_TERMCAP_mb || true
# Keep an obvious error color available for tools that look for $AIBOX_ERROR_COLOR.
export AIBOX_ERROR_SGR='38;2;229;91;91'
